### ISSUE TITLE
Add more video source. Singapore maybe?

### ISSUE THREAD

**Issue by dundeeyy** [goodtube4u/goodtube#25] opened 2024-07-16 03:56 UTC
I live in Southeast Asia (SEA) and it's so laggy, especially when watching a live stream.

**Comment by goodtube4u** [comment] 2024-07-16 07:04
Too laggy to use, or just slightly more slow than Youtube? Generally speaking the server location doesn't help too much as it has more to do with how decent they are.

I don't host or create video servers, but I will review the list soon and try to add in any that are closer to you. Hang tight!

**Comment by dundeeyy** [comment] 2024-07-16 09:02
Not laggy to use, but it's slow to load the video (buffering).

Thank you.

**Comment by goodtube4u** [comment] 2024-07-16 12:57
Hi, I have reviewed all of the available servers and managed to add a few that might help. They are not located in south east asia, but they might be a better speed in general.

The closest available server is in Japan - called "Sphynx (JP)".
Can you check if this one is faster for you (as you live closer)?

The top 5-6 DE and US servers may still be better for you, I am not sure. It would be good to know how it is working for you.

Unless I travel around the world this is hard for me to test! :)

**Comment by dundeeyy** [comment] 2024-07-17 04:30
Hi, Sphynx (JP) server is worse than the "Automatic" option.

Because from what I remember from playing online games, Japanese server latency is quite high from where I live, around 110-150ms.

I tested the US (Sphere) server, but I don't know why it's better than the DE and JP servers. And also I encountering less buffering than before.

But I just found new bug I think, sometimes (not often) when I switching between chrome tabs and go back to watch the live stream, the video is stuck/freeze but the audio is still playing.

**Comment by goodtube4u** [comment] 2024-07-17 11:47
These are the best servers I currently have access to so for now will have to do. Hopefully some more will be created soon, in which case I will add them. Not sure why the live stream would be pausing - but I do not have control over this, as that issue would also be caused by the stream provided by the server.

I might look into setting up "self hosted" servers soon and post instructions on the page - but it's quite difficult to do I think. This would be like using your own computer as the server, which would solve any speed / buffering / freezing issues.

Closing the issue for now, as there's not much else I can do at this stage.

Thanks for reporting and testing! If you have any other problems, feel free to open a new issue :)

**Closed by goodtube4u** 2024-07-17 11:47 UTC
