### ISSUE TITLE
unable to load video currently after update

### ISSUE THREAD

**Issue by marwintan** [goodtube4u/goodtube#43] opened 2024-09-16 08:10 UTC
after udpating , the video play till half then move to next video

**Comment by goodtube4u** [comment] 2024-09-16 08:55
Can you please give some more information? This hasn't been updated in a while so not sure what has changed for you.

**Comment by marwintan** [comment] 2024-09-16 16:26
i am playing mix playlist, after able to find the server, it will load the video for around 1 minute then it will skip to next video

**Comment by goodtube4u** [comment] 2024-09-16 22:42
Hmm. Sometimes this skipping through playlists is caused by other plugins. Can you try disabling your other adblockers and youtube plugins? These are probably what is causing this problem.

It's working ok for me, google chrome - windows 10.

Let me know if that helps.

**Comment by marwintan** [comment] 2024-09-17 03:11
i didnt have other plugin, only tampermonkey 

https://www.youtube.com/watch?v=-lR2Zib8PIo&list=RDMMAq8pDJkFQGw&index=5

i realised if i removed the index=5 in the link, it will be ok for this video

**Comment by goodtube4u** [comment] 2024-09-17 04:24
That link works for me, so closing as I cannot replicate this issue.

**Closed by goodtube4u** 2024-09-17 04:24 UTC
