### ISSUE TITLE
Unable to run live video

### ISSUE THREAD

**Issue by marwintan** [goodtube4u/goodtube#40] opened 2024-09-04 12:17 UTC
Kindly assist how to run live video, it shows that unable to find the server. thanks

**Comment by goodtube4u** [comment] 2024-09-04 21:59
Hi, there's been a number of issues with the servers lately. I don't host these or have control over them unfortunately, they're public youtube proxies.

Basically Youtube introduced some code that is causing them to have problems, but a fix has been created and with luck will be released soon.

This is also causing the long load times, etc.

So all I can say for now is to hang tight! Fingers crossed everything will work as intended soon.

**Closed by goodtube4u** 2024-09-04 21:59 UTC

**Comment by marwintan** [comment] 2024-09-07 03:53
Thanks for the reply , glad to be hear the fix will be out soon.
